# Theme settings
doks:
    baseurl: "https://dssoc.github.io"
    url: "https://dssoc.github.io"
    color_theme: blue

    header:
        logo:
            text: Data Science & Society
            image:
        nav:
            - item_name: Course Description
              item_url: '/course'
            - item_name: Schedule
              item_url: '/schedule'
            - item_name: Resources
              item_url: '/references'
    footer:
        content:
            logo:
                text: Data Science & Society 
                image:
            copyright: Copyright &copy; 2020, All rights reserved. <br> website background by <a href = "https://www.smithsonianmag.com/history/first-time-together-and-color-book-displays-web-du-bois-visionary-infographics-180970826/">W.E.B. Du Bois </a>
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/chris_bail'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/channel/UCqvvYami12pj3SYS2JIvzZg'


# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
